tt

diff --git a/.github/workflows/test_workflows.yml b/.github/workflows/test_workflows.yml
--- a/.github/workflows/test_workflows.yml
+++ b/.github/workflows/test_workflows.yml
@@ -1,27 +1,100 @@
-# workflow level env vars cannot be used at the job level
-# https://github.community/t/how-to-set-and-access-a-workflow-variable/17335/15
-name: Galaxy Workflow Tests for push and PR
-on: [push, pull_request]
+name: Workflows Linting and Testing
+on:
+  # Triggers the workflow on push or pull request events but only for the main branch
+  push:
+    branches: [ master ]
+  pull_request:
+    branches: [ master ]
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+  schedule:
+    # Run at midnight every monday
+    - cron: '0 0 * * 1'
+env:
+  GALAXY_FORK: galaxyproject
+  GALAXY_BRANCH: release_22.05
+  MAX_CHUNKS: 40
 jobs:
   setup:
     name: Setup cache and determine changed repositories
-    uses: ./.github/workflows/setup.yml
-    with:
-      python-version-list: "[\"3.7\"]"
-      galaxy-fork: galaxyproject
-      galaxy-branch: release_22.05
-      max-chunks: 4
-
-  # Planemo lint the changed repositories
-  lint:
-    name: Lint workflows
-    needs: setup
-    if: needs.setup.outputs.repository-list != ''
     runs-on: ubuntu-latest
+    outputs:
+      galaxy-head-sha: ${{ steps.get-galaxy-sha.outputs.galaxy-head-sha }}
+      fork: ${{ steps.get-fork-branch.outputs.fork }}
+      branch: ${{ steps.get-fork-branch.outputs.branch }}
+      repository-list: ${{ steps.discover.outputs.repository-list }}
+      chunk-count: ${{ steps.discover.outputs.chunk-count }}
+      chunk-list: ${{ steps.discover.outputs.chunk-list }}
     strategy:
       matrix:
         python-version: ['3.7']
     steps:
+    - name: Set galaxy fork and branch
+      id: get-fork-branch
+      run: |
+        TMP="${{ github.event.client_payload.slash_command.args.named.fork }}"
+        echo "fork=${TMP:-$GALAXY_FORK}" >> $GITHUB_OUTPUT
+        TMP="${{ github.event.client_payload.slash_command.args.named.branch }}"
+        echo "branch=${TMP:-$GALAXY_BRANCH}" >> $GITHUB_OUTPUT
+    - name: Determine latest commit in the Galaxy repo
+      id: get-galaxy-sha
+      run: echo "galaxy-head-sha=$(git ls-remote https://github.com/${{ steps.get-fork-branch.outputs.fork }}/galaxy refs/heads/${{ steps.get-fork-branch.outputs.branch }} | cut -f1)" >> $GITHUB_OUTPUT
+    - uses: actions/setup-python@v4
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Cache .cache/pip
+      uses: actions/cache@v3
+      id: cache-pip
+      with:
+        path: ~/.cache/pip
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ steps.get-galaxy-sha.outputs.galaxy-head-sha }}
+    # Install the `wheel` package so that when installing other packages which
+    # are not available as wheels, pip will build a wheel for them, which can be cached.
+    - name: Install wheel
+      run: pip install wheel
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 1
+    - name: Fake a Planemo run to update cache and determine commit range, repositories, and chunks
+      uses: galaxyproject/planemo-ci-action@v1
+      id: discover
+      with:
+        create-cache: ${{ steps.cache-pip.outputs.cache-hit != 'true' || steps.cache-planemo.outputs.cache-hit != 'true' }}
+        galaxy-fork: ${{ steps.get-fork-branch.outputs.fork }}
+        galaxy-branch: ${{ steps.get-fork-branch.outputs.branch }}
+        max-chunks: ${{ env.MAX_CHUNKS }}
+        python-version: ${{ matrix.python-version }}
+    - name: Show repository list
+      run: echo '${{ steps.discover.outputs.repository-list }}'
+    - name: Show chunks
+      run: |
+        echo 'Using ${{ steps.discover.outputs.chunk-count }} chunks (${{ steps.discover.outputs.chunk-list }})'
+
+  test:
+    name: Test tools
+    # This job runs on Linux
+    runs-on: ubuntu-latest
+    needs: setup
+    if: ${{ needs.setup.outputs.repository-list != '' }}
+    strategy:
+      fail-fast: false
+      matrix:
+        chunk: ${{ fromJson(needs.setup.outputs.chunk-list) }}
+        python-version: ['3.7']
+    services:
+      postgres:
+        image: postgres:11
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: postgres
+        ports:
+          - 5432:5432
+    steps:
+    # checkout the repository
+    # and use it as the current working directory
     - uses: actions/checkout@v3
       with:
         fetch-depth: 1
@@ -34,37 +107,41 @@ jobs:
       with:
         path: ~/.cache/pip
         key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
-    - name: Install wheel
-      run: pip install wheel
-    - name: Planemo lint workflows
+    - name: Get number of CPU cores
+      uses: SimenB/github-actions-cpu-cores@v1
+      id: cpu-cores
+    - name: Clean dotnet folder for space
+      run: rm -Rf /usr/share/dotnet
+    - name: Planemo test
       uses: galaxyproject/planemo-ci-action@v1
+      id: test
       with:
-        mode: lint
-        workflows: true
-        repository-list: "${{ needs.setup.outputs.repository-list }}"
+        mode: test
+        repository-list: ${{ needs.setup.outputs.repository-list }}
+        galaxy-fork: ${{ needs.setup.outputs.fork }}
+        galaxy-branch: ${{ needs.setup.outputs.branch }}
+        chunk: ${{ matrix.chunk }}
+        chunk-count: ${{ needs.setup.outputs.chunk-count }}
+        galaxy-slots: ${{ steps.cpu-cores.outputs.count }}
+        # Limit each test to 15 minutes
+        test_timeout: 900
+    - uses: actions/upload-artifact@v3
+      with:
+        name: 'Tool test output ${{ matrix.chunk }}'
+        path: upload
 
-  test:
-    name: Test workflows
-    needs: setup
-    if: needs.setup.outputs.repository-list != ''
-    uses: ./.github/workflows/run_tests.yml
-    with:
-      galaxy-head-sha: ${{ needs.setup.outputs.galaxy-head-sha }}
-      chunk-count: ${{ fromJSON(needs.setup.outputs.chunk-count) }}
-      chunk-list: ${{ needs.setup.outputs.chunk-list }}
-      python-version-list: "[\"3.7\"]"
-      repository-list: ${{ needs.setup.outputs.repository-list }}
-      galaxy-fork: galaxyproject
-      galaxy-branch: master
-      check-outputs: false
-
+  # - combine the results of the test chunks (which will never fail due
+  #   to `|| true`) and create a global test report as json and html which
+  #   is provided as artifact
+  # - check if any tool test actually failed (by lookup in the combined json)
+  #   and fail this step if this is the case
   combine_outputs:
-    # same as tool step
     name: Combine chunked test results
     needs: [setup, test]
     strategy:
       matrix:
         python-version: ['3.7']
+    # This job runs on Linux
     runs-on: ubuntu-latest
     steps:
     - uses: actions/download-artifact@v3
@@ -78,7 +155,7 @@ jobs:
       id: cache-pip
       with:
         path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_{{ needs.setup.outputs.galaxy-head-sha }}
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
     - name: Combine outputs
       uses: galaxyproject/planemo-ci-action@v1
       id: combine
@@ -89,6 +166,26 @@ jobs:
       with:
         name: 'All tool test results'
         path: upload
+    - name: Create URL to the run output
+      if: ${{ github.event.client_payload.slash_command.command == 'run-all-tool-tests' }}
+      id: vars
+      run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT
+
+    - name: Create comment
+      if: ${{ github.event.client_payload.slash_command.command == 'run-all-tool-tests' }}
+      uses: peter-evans/create-or-update-comment@v2
+      with:
+        token: ${{ secrets.PAT }}
+        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
+        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
+        body: |
+          Summary:
+
+          ${{ steps.combine.outputs.statistics }}
+
+          [Find all tool test results here][1]
+
+          [1]: ${{ steps.vars.outputs.run-url }}
     - name: Check outputs
       uses: galaxyproject/planemo-ci-action@v1
       id: check
